### ISSUE TITLE
Lägg till att "dom" också är ett korrekt alternativ om man inte orkar lära sig regeln!

### ISSUE THREAD

**Issue by Bryntet** [Lauler/sprakpolisen#2]
Enligt SAOL så är "dom" alltid korrekt, så kan du inte lägga till nån liten text i kommentaren som båten lämnar där det förklaras att "dom" också är ett alternativ som funkar och dessutom alltid är korrekt!

**Comment by Lauler** [comment]
Även om "dom" är accepterat har det en tydlig vardaglig och talspråklig prägel. Språkrådet [skriver](https://spraktidningen.se/2019/06/talar-framtiden-de-dem-eller-dom/):

> Den som använder dom riskerar att uppfattas som en person som inte behärskar standardnormen.

Fram till förra året stod det i Svensk Ordbok:

> Den talspråkliga formen dom har tidvis förekommit i skriftspråk, även i seriösa texter av erkänt skickliga skribenter. För närvarande kan den dock knappast användas i skrift utan att texten får en mycket vardaglig prägel. Det bör dock sägas att formen dom gör det möjligt för mindre vana skribenter att undvika fel som "han såg de inte" och "dem såg honom inte".

Formen "dom" har fortfarande noteringen <vardaglig> i Svensk Ordbok. 

SpråkpolisenBot rättar aldrig någon som använder "dom". Botten rättar endast de som försöker använda "de" och "dem", och tar fel. Botten har vid många tillfällen också fått [kritik och feedback](https://www.reddit.com/r/sweden/comments/ubgl37/omr%C3%B6stning_spr%C3%A5kpolisenbot/) om att den bör korta ned sina inlägg. Därför har inläggen kortats ned och all text som kan uppfattas som överflödig tagits bort. 

Jag tror inte, som bottens skapare, heller att det är sannolikt att "dom" någonsin kommer få fäste i det svenska språket, såvida det inte sker via tvång (medveten språkreform i skolor och tidningar). Jag utvecklar mina tankar om varför i [följande kommentar](https://www.reddit.com/r/sweden/comments/sjqvgi/comment/hvgr0uf/?utm_source=reddit&utm_medium=web2x&context=3). Jag kommer därmed tyvärr inte att lägga till någon text om "dom".

**Comment by augustuslego** [comment]
Fullt rimligt! Ha en fortsatt trevlig dag :)

**Comment by Lauler** [comment]
Tack för feedback och ha en fortsatt trevlig dag!
